### ISSUE TITLE
There's some problem w dis filter on the TikTok app

### ISSUE THREAD

**Issue by Cytcrow** [h1toru/filterlist#1]
Profile Picture does not load along with the thumbnail video in "Watch history"

This is the description of my TikTok:
Package name: com.ss.android.ugc.trill
Version: 36.4.4
Package source: Play store

I'm making this post to let you know if you didn't realize there was a problem with the app.
![Screenshot_2024-09-21-00-18-57-966_com ss android ugc trill](https://github.com/user-attachments/assets/fbc4b1d5-6e22-4c93-a507-4f06a2557990)
![Screenshot_2024-09-21-00-16-07-210_com ss android ugc trill](https://github.com/user-attachments/assets/ea26eaa8-f7f2-4c74-8e40-1e5826acaf70)
![Screenshot_2024-09-20-06-06-11-821_com ss android ugc trill](https://github.com/user-attachments/assets/e71b55d8-ae6a-41af-a730-aaf8de0b31f3)
![Screenshot_2024-09-21-00-15-53-772_com ss android ugc trill](https://github.com/user-attachments/assets/14d155d4-66ba-4bcd-89af-eb1e48d5099f)

The thing is I don't know anything about these things so Im not really sure how to help fixing this problem so I just gonna give u the package description I'm using...

**Comment by Cytcrow** [comment]
The thing is I don't know anything about these things so Im not really sure how to help fixing this problem so I just gonna give u the TikTok package I'm using...

**Comment by h1toru** [comment]
make sure you know what you're getting into.

it's literally written on the page:
https://github.com/h1toru/filterlist/blob/6406ffbc44b23d0d9f9847f1117422e6f71f83c0/README.md?plain=1#L40

"**Block TikTok completely**" means it supposed to blocks access to TikTok.  
it's a filterlist for someone who wants to block access to TikTok or don't want to connect to any TikTok domains.

**Comment by h1toru** [comment]
if you want to to block TikTok ads/analytics/tracker only there will be another filterlist which i'm currently making. i'll give an update when its uploaded.

**Comment by Cytcrow** [comment]
Ahh I see mb bro
